services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 30s
      retries: 5
  bot:
    image: crm
    container_name: crmbot
    build: .
    restart: always
    depends_on:
      db:
          condition: service_healthy
