version: '3.8'
services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5433:5432"
